"""Add lawyer tables and update group message author

Revision ID: 142db7ec9e62
Revises: 50ec91252199
Create Date: 2025-12-01 20:33:15.326932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '142db7ec9e62'
down_revision: Union[str, None] = '50ec91252199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyername', sa.String(), nullable=False),
    sa.Column('lawyername_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('specializations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyers_id'), 'lawyers', ['id'], unique=False)
    op.create_index(op.f('ix_lawyers_lawyername'), 'lawyers', ['lawyername'], unique=True)
    op.create_table('lawyer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyername', sa.String(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lawyername'], ['lawyers.lawyername'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_reviews_id'), 'lawyer_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_lawyer_reviews_lawyername'), 'lawyer_reviews', ['lawyername'], unique=False)
    op.create_table('lawyer_groups',
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ondelete='CASCADE')
    )
    op.add_column('group_messages', sa.Column('lawyer_author_id', sa.Integer(), nullable=True))
    op.alter_column('group_messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'group_messages', 'lawyers', ['lawyer_author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('group_messages', 'is_evidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_messages', sa.Column('is_evidence', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_messages', type_='foreignkey')
    op.alter_column('group_messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('group_messages', 'lawyer_author_id')
    op.drop_table('lawyer_groups')
    op.drop_index(op.f('ix_lawyer_reviews_lawyername'), table_name='lawyer_reviews')
    op.drop_index(op.f('ix_lawyer_reviews_id'), table_name='lawyer_reviews')
    op.drop_table('lawyer_reviews')
    op.drop_index(op.f('ix_lawyers_lawyername'), table_name='lawyers')
    op.drop_index(op.f('ix_lawyers_id'), table_name='lawyers')
    op.drop_table('lawyers')
    # ### end Alembic commands ###
