"""iluvshibuki

Revision ID: f6a181086d6f
Revises: 142db7ec9e62
Create Date: 2025-12-02 00:16:54.987438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f6a181086d6f'
down_revision: Union[str, None] = '142db7ec9e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_reviews', sa.Column('lawyer_id', sa.Integer(), nullable=False))
    op.add_column('lawyer_reviews', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('lawyer_reviews', sa.Column('case_type', sa.Enum('DELIVERY', 'INSURANCE', 'DOOR_TO_DOOR', 'APPOINTMENT', 'RENTAL', 'ROMANCE', 'SMISHING', 'FALSE_ADVERTISING', 'SECONDHAND_FRAUD', 'INVESTMENT_SCAM', 'ACCOUNT_TAKEOVER', 'OTHER', name='casetype'), nullable=False))
    op.drop_index(op.f('ix_lawyer_reviews_lawyername'), table_name='lawyer_reviews')
    op.create_index(op.f('ix_lawyer_reviews_author_id'), 'lawyer_reviews', ['author_id'], unique=False)
    op.drop_constraint(op.f('lawyer_reviews_lawyername_fkey'), 'lawyer_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'lawyer_reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lawyer_reviews', 'lawyers', ['lawyer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lawyer_reviews', 'lawyername')
    op.add_column('lawyers', sa.Column('username', sa.String(), nullable=False))
    op.add_column('lawyers', sa.Column('lawyer_name', sa.String(), nullable=True))
    op.alter_column('lawyers', 'specializations',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Enum('DELIVERY', 'INSURANCE', 'DOOR_TO_DOOR', 'APPOINTMENT', 'RENTAL', 'ROMANCE', 'SMISHING', 'FALSE_ADVERTISING', 'SECONDHAND_FRAUD', 'INVESTMENT_SCAM', 'ACCOUNT_TAKEOVER', 'OTHER', name='casetype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_lawyers_lawyername'), table_name='lawyers')
    op.create_index(op.f('ix_lawyers_username'), 'lawyers', ['username'], unique=True)
    op.drop_column('lawyers', 'display_name')
    op.drop_column('lawyers', 'lawyername')
    op.drop_column('lawyers', 'lawyername_changed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('lawyername_changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('lawyers', sa.Column('lawyername', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lawyers', sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_lawyers_username'), table_name='lawyers')
    op.create_index(op.f('ix_lawyers_lawyername'), 'lawyers', ['lawyername'], unique=True)
    op.alter_column('lawyers', 'specializations',
               existing_type=sa.Enum('DELIVERY', 'INSURANCE', 'DOOR_TO_DOOR', 'APPOINTMENT', 'RENTAL', 'ROMANCE', 'SMISHING', 'FALSE_ADVERTISING', 'SECONDHAND_FRAUD', 'INVESTMENT_SCAM', 'ACCOUNT_TAKEOVER', 'OTHER', name='casetype'),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.drop_column('lawyers', 'lawyer_name')
    op.drop_column('lawyers', 'username')
    op.add_column('lawyer_reviews', sa.Column('lawyername', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lawyer_reviews', type_='foreignkey')
    op.drop_constraint(None, 'lawyer_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('lawyer_reviews_lawyername_fkey'), 'lawyer_reviews', 'lawyers', ['lawyername'], ['lawyername'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lawyer_reviews_author_id'), table_name='lawyer_reviews')
    op.create_index(op.f('ix_lawyer_reviews_lawyername'), 'lawyer_reviews', ['lawyername'], unique=False)
    op.drop_column('lawyer_reviews', 'case_type')
    op.drop_column('lawyer_reviews', 'author_id')
    op.drop_column('lawyer_reviews', 'lawyer_id')
    # ### end Alembic commands ###
